### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by mrniddala** [fishcute/Celestial#1]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_27983()" because "net.minecraft.class_310.method_1551().field_1687" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at fishcute.celestial.sky.CelestialSky.getDimensionRenderInfo(CelestialSky.java:34)
	at net.minecraft.client.render.WorldRenderer.renderCustomStars(WorldRenderer:8279)
	at net.minecraft.client.render.WorldRenderer.handler$ekg000$injectRenderStars(WorldRenderer:3510)
	at net.minecraft.client.render.WorldRenderer.renderStars(WorldRenderer)
	at net.minecraft.client.render.WorldRenderer.renderStars(WorldRenderer:673)
	at net.minecraft.client.render.WorldRenderer.<init>(WorldRenderer:301)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:583)
	at net.minecraft.client.main.Main.method_44604(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fishcute.celestial.sky.CelestialSky.getDimensionRenderInfo(CelestialSky.java:34)
	at net.minecraft.class_761.renderCustomStars(class_761.java:8279)
	at net.minecraft.class_761.handler$ekg000$injectRenderStars(class_761.java:3510)
	at net.minecraft.class_761.method_3255(class_761.java)
	at net.minecraft.class_761.method_3293(class_761.java:673)
	at net.minecraft.class_761.<init>(class_761.java:301)
	at net.minecraft.class_310.<init>(class_310.java:583)

**Comment by fishcute** [comment]
Is this on 1.0.0 or 1.0.1?

**Comment by mrniddala** [comment]
Uh, fast! It is the latest version 1.0.1 on 1.19.2.
I am using Custom Stars too, not sure if this is related to this bug: https://www.curseforge.com/minecraft/mc-mods/custom-stars

**Comment by fishcute** [comment]
Custom stars may be the problem, although I can't be sure. Try running the mod without Custom stars and let me know the result.

**Comment by mrniddala** [comment]
Yep, removing Custom Stars resolved the problem for me.

**Comment by fishcute** [comment]
Alright. Celestial has its own star customization system, so there might have been some conflict there.

**Comment by mrniddala** [comment]
So there is no compatibility workaround possible?

**Comment by fishcute** [comment]
Probably not. Whatever you are trying to do can probably be accomplished with Celestial, so you could try that.

**Comment by mrniddala** [comment]
Alright, thanks.
